PetShopWebApplication/Models/Shop.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetShopWebApplication.Models
{
    public class Shop
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required(ErrorMessage = "Поле повинно бути встановлено")]
        public int ID { get; set; }

        [StringLength(30)]
        [Display(Name = "Назва магазину")]
        [Required(ErrorMessage = "Поле повинно бути встановлено")]
        public string Name { get; set; }

        [Display(Name = "Адреса магазину")]
        [Required(ErrorMessage = "Поле повинно бути встановлено")]
        [StringLength(35)]
        public string Adress { get; set; }

        //public ICollection<Animal> Animals { get; set; }
        [Display(Name = "Список кліток")]
        public ICollection<Cage> Cages { get; set; }
    }
    
    
}

PetShopWebApplication/Controllers/CagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetShopWebApplication.Data;
using PetShopWebApplication.Models;

namespace PetShopWebApplication.Controllers
{
    public class CagesController : Controller
    {
        private readonly AnimalsContext _context;
        private static int shopId;

        public CagesController(AnimalsContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Details(int? id)
        {
            shopId = (int)id;
            var animalsContext = _context.Cages.Where(c=>c.ShopID==shopId).Include(c => c.Shop);
            return View(await animalsContext.ToListAsync());
        }

        // GET: Cages/Create
        public IActionResult Create()
        {
            var cage = new Cage();
            cage.ShopID = shopId;
            cage.Shop = _context.Shops.Where(s => s.ID == shopId).First();
            return View(cage);
        }

        // POST: Cages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Number,Square")] Cage cage)
        {
            cage.ID = Guid.NewGuid().GetHashCode();
            cage.ShopID = shopId;
            if (ModelState.IsValid)
            {
                _context.Add(cage);
                await _context.SaveChangesAsync();
                return Redirect("https://localhost:44324/Cages/Details/" + shopId);
            }
            return View(cage);
        }

        // GET: Cages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var cage = await _context.Cages.FindAsync(id);
            if (cage == null)
            {
                return NotFound();
            }
            return View(cage);
        }

        // POST: Cages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ShopID,Number,Square")] Cage cage)
        {
            cage.ShopID = shopId;
            cage.Shop = _context.Shops.Where(s => s.ID == shopId).First();
            if (id != cage.ID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CageExists(cage.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("https://localhost:44324/Cages/Details/"+shopId);
            }
            return View(cage);
        }

        // GET: Cages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cage = await _context.Cages
                .Include(c => c.Shop)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (cage == null)
            {
                return NotFound();
            }

            return View(cage);
        }

        // POST: Cages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cage = await _context.Cages.FindAsync(id);
            _context.Cages.Remove(cage);
            await _context.SaveChangesAsync();
            return Redirect("https://localhost:44324/Cages/Details/" + shopId);
        }

        private bool CageExists(int id)
        {
            return _context.Cages.Any(e => e.ID == id);
        }
    }
}

PetShopWebApplication/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetShopWebApplication.Data;
using PetShopWebApplication.Models;

namespace PetShopWebApplication.Controllers
{
    public class ShopsController : Controller
    {
        private readonly AnimalsContext _context;

        public ShopsController(AnimalsContext context)
        {
            _context = context;
        }

        // GET: Shops
        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            try
            {
                int n = int.Parse(searchString);
                var shops = _context.Shops.Where(s => s.Cages.Count >= n);
                return View(await shops.ToListAsync());
            }
            catch (Exception)
            {
                return View(await _context.Shops.ToListAsync());
            }
        }

        // GET: Shops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shops
                .Include(s => s.Cages)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // GET: Shops/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Adress")] Shop shop)
        {
            shop.ID = Guid.NewGuid().GetHashCode();
            if (ModelState.IsValid)
            {
                _context.Add(shop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shops.FindAsync(id);
            if (shop == null)
            {
                return NotFound();
            }
            return View(shop);
        }

        // POST: Shops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Adress")] Shop shop)
        {
            if (id != shop.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopExists(shop.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shops/Delete/5
        public async Task<IActionResult> Delete(int? id,string errorMessage)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shops
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (shop == null)
            {
                return NotFound();
            }
            ViewData["ErrorMessage"] =errorMessage;
            return View(shop);
        }

        // POST: Shops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shop = await _context.Shops.FindAsync(id);
            int animalsCount = _context.Animals.Where(a => a.ShopID == id).Count();
            if (animalsCount == 0)
            {
                var cages = _context.Cages.Where(c => c.ShopID == id).ToList();
                foreach(Cage cage in cages)
                    _context.Cages.Remove(cage);
                _context.Shops.Remove(shop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
                return RedirectToAction(nameof(Delete), new { id = id, errorMessage = "Неможливо видалити магазин, у якому є тварини" });
        }

        private bool ShopExists(int id)
        {
            return _context.Shops.Any(e => e.ID == id);
        }
    }
}

PetShopWebApplication/Views/Shops/Create.cshtml
@model PetShopWebApplication.Models.Shop

@{
    ViewData["Title"] = "Create";
}

<h1>Додавання</h1>

<h4>Новий магазин</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Додати" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутися до таблиці магазинів</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PetShopWebApplication/Views/Shops/Delete.cshtml
@model PetShopWebApplication.Models.Shop

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалення</h1>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Ви впевнені, що хочете видалити цей магазин?</h3>
<div>
    <h4>Інформація про магазин</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Повернутися до таблиці магазинів</a>
    </form>
</div>

PetShopWebApplication/Views/Shops/Details.cshtml
@model PetShopWebApplication.Models.Shop

@{
    ViewData["Title"] = "Details";
}

<h1>Детальна інформація</h1>

<div>
    <h4>Магазин</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cages)
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Номер клітки</th>
                    <th>Площа</th>
                </tr>
                @foreach (var item in Model.Cages)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Number)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Square)
                        </td>
                    </tr>
                }
            </table>
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Редагувати інформацію про магазин</a> |
    <a asp-controller="Cages" asp-action="Details" asp-route-id="@Model.ID">Редагувати інформацію про клітки</a> |
    <a asp-action="Delete" asp-route-id="@Model.ID">Видалити</a> |
    <a asp-action="Index">Повернутися до таблиці магазинів</a>
</div>

PetShopWebApplication/Views/Shops/Edit.cshtml
@model PetShopWebApplication.Models.Shop

@{
    ViewData["Title"] = "Edit";
}

<h1>Редагувати інформацію</h1>

<h4>Магазин</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            
                <div class="form-group">
                    <input type="submit" value="Зберегти зміни" class="btn btn-primary" />
                </div>
            </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутися до таблиці магазинів</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PetShopWebApplication/Views/Shops/Index.cshtml
@model IEnumerable<PetShopWebApplication.Models.Shop>

@{
    ViewData["Title"] = "Index";
}

<h1>Магазини</h1>

<p>
    <a asp-action="Create">Додати новий магазин</a>
</p>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Знайти магазини за мінімальною кількістю кліток: <input type="text" name="SearchString" value="@ViewBag.СurrentFilter" />
            <input type="submit" value="Шукати" class="btn btn-default" /> |
            <a asp-action="Index">Повернутися до повного списку</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adress)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adress)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Редагувати інформацію про магазин</a>|
                    <a asp-controller="Cages" asp-action="Details" asp-route-id="@item.ID">Редагувати інформацію про клітки</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Детальніше</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Видалити</a>
                </td>
            </tr>
        }
    </tbody>
</table>